import { Onest } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from '@/components/Footer';
import PreLoader from '@/components/PreLoader';
import AuthProvider from '@/services/AuthProvider';

const onest = Onest({
  subsets: ['latin'], // You can specify the subsets (e.g., latin, latin-ext)
  weight: ['400', '500', '600', '700', '800'], // Specify the weights you need
});


export const metadata = {
  title: "Next Task Project",
  description: "Generated by M B Subhana",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={onest.className}
      >
        
          <PreLoader></PreLoader>
          <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          </AuthProvider>
        
      </body>
    </html>
  );
}
